services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportsrental
    ports:
      - "3306:3306"
    volumes:
      - danilo_test_data:/var/lib/mysql

volumes:
  danilo_test_data: