version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/sportsrental
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - springboot-network
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sportsrental
    ports:
      - "3306:3306"
    networks:
      - springboot-network
    restart: always
    volumes:
      - dbdata:/var/lib/mysql

networks:
  springboot-network:
    driver: bridge

volumes:
  dbdata:
